### ISSUE TITLE
Reorganize api endpoints

### ISSUE THREAD

**Issue by 3TUSK** [teaconmc/Biluochun#1]
- Move `/dashboard` to `/api/dashboard`
 - Move `/login` to `/api/login`
 - `POST /dashboard/team/new` to `POST /dashboard/team`
   - `POST /dashboard/team/:team_name`?
 - `POST /dashboard/update` to `PATCH /dashboard/` or something alike
   - `PATCH /dashboard/me`?
   - Separate the team updates to `/dashboard/team`?

**Comment by 3TUSK** [comment]
Also ping @Yesterday17 for comments.

**Comment by Yesterday17** [comment]
- `/dashboard/avatar` -> `/api/avatar`?

**Comment by 3TUSK** [comment]
https://github.com/teaconmc/Biluochun/compare/49cf054...6a5a842
